# Source link : https://www.youtube.com/watch?v=zWyggxV51oQ

version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=lamp_docker
      - MYSQL_USER=lamp_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp_docker

  www:
    depends_on:
      - db
    image: php:8.2-apache

    #custom build to include mysqli into the "php_custom" folder 
    build: ./php_custom 
    
    volumes:
      - "./:/var/www/html"
    ports:
      - 89:80
      - 443:443
    networks:
      - lamp_docker

  phpmyadmin: 
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp_docker
networks:
  lamp_docker:
    driver: bridge



